version: '3'
services:
  web:
    build: .
    ports:
     - "80:80"
  mysql:
    image: "mysql:5.7"
    container_name: "mysql-for-python"
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_USER=dev"
      - "MYSQL_PASS=Cango666"
    ports:
      - "3307:3306"
      